import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/home/home').then(m => m.Home) },
  { path: 'admisiones',         loadComponent: () => import('./pages/admisiones/admisiones').then(m => m.Admisiones) },
  { path: 'alumni',             loadComponent: () => import('./pages/alumni/alumni').then(m => m.Alumni) },
  { path: 'noticias',           loadComponent: () => import('./pages/noticias/noticias').then(m => m.Noticias) },
  { path: 'oferta-educativa',   loadComponent: () => import('./pages/oferta-educativa/oferta-educativa').then(m => m.OfertaEducativa) },
  { path: 'infantil',           loadComponent: () => import('./pages/infantil/infantil').then(m => m.Infantil) },
  { path: 'primaria',           loadComponent: () => import('./pages/primaria/primaria').then(m => m.Primaria) },
  { path: 'secundaria',         loadComponent: () => import('./pages/secundaria/secundaria').then(m => m.Secundaria) },
  { path: 'bachillerato',       loadComponent: () => import('./pages/bachillerato/bachillerato').then(m => m.Bachillerato) },
  { path: 'fp',                 loadComponent: () => import('./pages/fp/fp').then(m => m.Fp) },
  { path: 'proyecto-educativo', loadComponent: () => import('./pages/proyecto-educativo/proyecto-educativo').then(m => m.ProyectoEducativo) },
  { path: 'single-sex',         loadComponent: () => import('./pages/single-sex/single-sex').then(m => m.SingleSex) },
  { path: 'bilinguismo',        loadComponent: () => import('./pages/bilinguismo/bilinguismo').then(m => m.Bilinguismo) },
  { path: 'ipad',               loadComponent: () => import('./pages/ipad/ipad').then(m => m.Ipad) },
  { path: 'becas',              loadComponent: () => import('./pages/becas/becas').then(m => m.Becas) },
  { path: 'ampa',               loadComponent: () => import('./pages/ampa/ampa').then(m => m.Ampa) },
  { path: 'instalaciones',      loadComponent: () => import('./pages/instalaciones/instalaciones').then(m => m.Instalaciones) },
  { path: 'historia',           loadComponent: () => import('./pages/historia/historia').then(m => m.Historia) },
  { path: 'mision-vision',      loadComponent: () => import('./pages/mision-vision/mision-vision').then(m => m.MisionVision) },
  { path: 'que-es-tajamar',     loadComponent: () => import('./pages/que-es-tajamar/que-es-tajamar').then(m => m.QueEsTajamar) },
  { path: 'opus-dei',           loadComponent: () => import('./pages/opus-dei/opus-dei').then(m => m.OpusDei) },
  { path: 'comedor',            loadComponent: () => import('./pages/comedor/comedor').then(m => m.Comedor) },
  { path: 'uniforme',           loadComponent: () => import('./pages/uniforme/uniforme').then(m => m.Uniforme) },
  { path: 'calendario',         loadComponent: () => import('./pages/calendario/calendario').then(m => m.Calendario) },
  { path: 'servicios',          loadComponent: () => import('./pages/servicios/servicios').then(m => m.Servicios) },
  { path: 'secretaria',         loadComponent: () => import('./pages/secretaria/secretaria').then(m => m.Secretaria) },
  { path: 'intranet',           loadComponent: () => import('./pages/intranet/intranet').then(m => m.Intranet) },
  { path: 'noticia-admisiones', loadComponent: () => import('./pages/noticia-admisiones/noticia-admisiones').then(m => m.NoticiaAdmisiones) },
  { path: 'noticia-alumni-lab', loadComponent: () => import('./pages/noticia-alumni-lab/noticia-alumni-lab').then(m => m.NoticiaAlumniLab) },
  { path: 'noticia-reflejos',   loadComponent: () => import('./pages/noticia-reflejos/noticia-reflejos').then(m => m.NoticiaReflejos) },
  { path: 'aviso-legal',        loadComponent: () => import('./pages/aviso-legal/aviso-legal').then(m => m.AvisoLegal) },
  { path: 'privacidad',         loadComponent: () => import('./pages/privacidad/privacidad').then(m => m.Privacidad) },
  { path: 'cookies',            loadComponent: () => import('./pages/cookies/cookies').then(m => m.Cookies) },
  { path: 'canal-denuncias',    loadComponent: () => import('./pages/canal-denuncias/canal-denuncias').then(m => m.CanalDenuncias) },
  { path: '**', redirectTo: '' }
];
